
# -*- coding: utf-8 -*-
"""
@author: Eric Guo <guoanjie@gmail.com>
@brief: one feature conf

Generated by
python get_feature_conf_SuarezAteMyTacos.py -d 10 -o feature_conf_SuarezAteMyTacos.py

Format:
FEATURE_NAME : (MANDATORY, TRANSFORM)

"""

import config
from feature_transformer import SimpleTransform, ColumnSelector

LSA_COLUMNS = range(10)

feature_dict = {

'SuarezAteMyTacos_braycurtis_distance_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_canberra_distance_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_char_diff_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_char_diff_unq_stop_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_char_ratio_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_cityblock_distance_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_common_words_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_cosine_distance_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_diff_len_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_fuzz_WRatio_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_fuzz_partial_ratio_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_fuzz_partial_token_set_ratio_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_fuzz_partial_token_sort_ratio_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_fuzz_qratio_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_fuzz_token_set_ratio_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_fuzz_token_sort_ratio_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_jaccard_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_kur_q1vec_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_len_char_q1_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_len_char_q2_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_len_q1_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_len_q2_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_len_word_q1_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_len_word_q2_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_minkowski_distance_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_norm_wmd_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_q1_freq_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_q1_q2_intersect_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_q2_freq_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_same_start_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_skew_q1vec_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_skew_q2vec_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_tfidf_wm_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_tfidf_wm_stops_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_total_unique_words_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_total_unq_words_stop_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_wc_diff_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_wc_diff_unique_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_wc_diff_unq_stop_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_wc_ratio_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_wc_ratio_unique_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_wc_ratio_unique_stop_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_wmd_1D' : (True, SimpleTransform()),
'SuarezAteMyTacos_word_match_1D' : (True, SimpleTransform()),
}
